GET https://vercel.com/leciane-silva12as-projects/backend_filmes/

###
POST https://vercel.com/leciane-silva12as-projects/backend_filmes/create
Content-Type: application/json

{
    "title": "Homem-Aranha: Sem Volta Pra Casa",
    "gender": "Ação",
    "ageLimit": 12,
    "duration": 149
}

###
DELETE https://vercel.com/leciane-silva12as-projects/backend_filmes/delete/12

###
PUT https://vercel.com/leciane-silva12as-projects/backend_filmes/update/2
Content-Type: application/json

{
    "title": "Senhor dos Anéis: As duas torres",
    "gender": "Fantasia / Ação",
    "ageLimit": 18,
    "duration": 187
}